AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  ImageId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cf-demos/ssm-params/default-us-east-2-amzlinux2-ami
  InstanceType:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cf-demos/ssm-params/default-instance-type

Resources: 
  EC2WithSSMParam:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
