AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys an application server within the public subnet of the
  simple vpc CF stack as well as a secure database server in the private subnet.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  
  NetworkStackName:
    Description: The EnvironmentName of the Simple VPC CloudFormation stack which is used in several places to reference exported output values from the network stack.
    Type: String
  
  
  

Mappings: 

Conditions: 

Resources: 

Outputs: