AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  SSHKey:
    Type:  AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH Access to the instance 

Resources: 
  EC2AppServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a0ad6b70e61be944
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
    
  EC2DbServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a0ad6b70e61be944
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref PostgresSecurityGroup
      

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref ServerSgDescription
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  PostgresSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Proeprties:
      GroupDescription: Provides Public Access to Postgres Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0