AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  SSHKey:
    Type:  AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH Access to the instance 

Resources:
  EC2WithUserData:
    Type: AWS::EC2::Instance 
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-0a0ad6b70e61be944
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      SecurityGroups:
        - !Ref SSHSecurityGroup
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r EC2WithUserData --region ${AWS::Region} || error_exit 'Failed to run cfn-init'

    Metadata:
      Comment: Install a Apache httpd and a webpage
      AWS::CloudFormation::Init: 
        config:
          packages:
            yum:
              httpd: []
            files:
              "/var/www/html/index.html":
                content: |
                  <h1>Hello World from EC2 instance!</h1>
                  <p>This was created using cfn-init</p>
                mode: '000644'
            commands:
              hello:
                command: "echo 'hello world'"
              starthttpd:
                command: "systemctl start httpd && systemctl enable httpd"
            # services:
            #   sysvinit:
            #     httpd:
            #       enabled: 'true'
            #       ensureRunning: 'true'

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp

Outputs:
  EC2WithUserDataPublicDNS:
    Description: The public DNS of this EC2 instance
    Value: !GetAtt EC2WithUserData.PublicDnsName
    Export:
      Name: EC2WithUserDataPublicDNS
